version: '3.9'
services:
  job:
    build: .
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      DATABASE_URL: file:/data/grocery.db
    volumes:
      - db-data:/data
    command: ["node", "dist/index.js"]

  # Example of a simple infinite loop to run every 24h inside container
  cron:
    build: .
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      DATABASE_URL: file:/data/grocery.db
    volumes:
      - db-data:/data
    command: ["bash", "-lc", "while true; do node dist/index.js; sleep 86400; done"]

volumes:
  db-data: